const ADD_CHARACTER='ADD_CHARACTER';
const DELETE_CHARACTER='DELETE_CHARACTER';
const FILTER='FILTER';
const ORDER='ORDER';

module.exports={
    ADD_CHARACTER,
    DELETE_CHARACTER,
    FILTER,
    ORDER
};